---
- name: Install Apache Web Server and Deploy Static Site
  hosts: all
  become: true

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Copy Static Web App
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Apache is Running
      service:
        name: apache2
        state: started
        enabled: true
